// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niwmjfpyetfhthwloqms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pd21qZnB5ZXRmaHRod2xvcW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjUxMzQsImV4cCI6MjA2NTEwMTEzNH0.DgAMcL_Eyf-Bx75pppKadlNrtlfzqH3SCgplo2bkJc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);